### PR TITLE
small typo in docs

### PR DESCRIPTION
**Pull request by steinkel**

### CODE REVIEW

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ide-helper/blob/master/src/IdeHelperPlugin.php#L44-L45
?

**Comment by steinkel** [comment]
the order was incorrect, it should say `bin/cake phpstorm generate`

**Comment by dereuromark** [comment]
No, that was in 4.x, in 5.x (master) it is as documented and linked in code.

**Comment by steinkel** [comment]
Ah! that was my issue then, I've used it in 4.x so the confusion, closing...

**Pull request closed without merging**
