### PR TITLE
Allow support for more complex array annotations

### PR DESCRIPTION
**Pull request by dereuromark**
Refs https://github.com/dereuromark/cakephp-ide-helper/issues/343

### CODE REVIEW

**Comment by Harfusha** [comment]
It works except for multiline type (multiline type works for vscode and phpstan)

image

(When i remove the generated annotation)
image

**Comment by Harfusha** [comment]
And will you backport it for Cakephp 4? I had to change vendor file for the test :D

**Comment by dereuromark** [comment]
Feel free to PR multiline support

also feel free to backport this to 4.x

Currently I dont have the time here.

**Comment by Harfusha** [comment]
I will try to do it later on (This is still magic for me, but i will figure it out)

**Pull request merged**
