### PR TITLE
Fix controller model annotating for plugins.

### PR DESCRIPTION
**Pull request by dereuromark**
This solves the issue of https://github.com/dereuromark/cakephp-ide-helper/issues/128 for now

The core itself is a bit dirty here as it sets a guessed/inflected name even if set to false. 
But thats another issue.

### CODE REVIEW

**Comment by dakota** [comment]
Fix is to change the if statement to `if ($this->getConfig(static::CONFIG_PLUGIN) && strpos('.', $modelClass) === false) {`. The modelClass building code in core already includes the plugin name in most cases.

**Comment by dereuromark** [comment]
Are you sure? For me this worked. I tested it on a plugin with controllers partially having the false and partially not.

**Comment by dakota** [comment]
Actually, no, that doesn't fix it. Doing some more investigation

**Comment by dakota** [comment]
Lol, well, it wouldn't fix it because I did the `strpos` argument wrongly. Should be `strpos('.', $modelClass) === false`

But, the change as is definately does change existing correct annotations (e.g. `\Plugin\Model\Table\UsersTable $Users`) to be incorrect (`\Cake\ORM\Table`)

**Comment by dereuromark** [comment]
I see - that is sure not a good idea then. Are you able to open a PR that fixes it the right way?
And do you agree that the core change is good for 3.8 and approve it please then?

**Comment by dereuromark** [comment]
Replacd by https://github.com/dereuromark/cakephp-ide-helper/pull/130

**Pull request closed without merging**
