### PR TITLE
Add load identifier task

### PR DESCRIPTION
**Pull request by toggenation**
Hi @dereuromark, This is my attempt at a PR to add type hinting to the AuthenticationService::loadIdentifier() method

I think the reason your phpstorm meta file works in VSCode is the PHP Intelephense plugin (bmewburn.vscode-intelephense-client).

I've tried to write a test but I'm not sure it's right. When I run it, it succeeds and then randomly fails.

Also I don't know how to squash these commits into one... still a git newbie.

Hope you can use it despite this.

Thanks for this plugin. Very useful

### CODE REVIEW

**Comment by dereuromark** [comment]
Hi!
I wonder since this isnt a native core topic, but a plugin:
https://github.com/dereuromark/cakephp-ide-helper#more
Wouldnt it be better suited in the IdeHelperExtra one?

Otherwise looks good :)

**Comment by toggenation** [comment]
Hi!

Okay, Will have a look at how to move it into more [https://github.com/dereuromark/cakephp-ide-helper-extra](https://github.com/dereuromark/cakephp-ide-helper-extra)

Apologies @dereuromark I'm bumping up to the limit of my understanding on this so may need to take a while to figure out how to move it into the IdeHelperExtra plugin... 

Maybe if I do a YT video on it I will understand it. Seems to become clear when having to explain it to others.

Thanks again I used `bin/cake annotate controllers` and it immediately fixed the $this->Authentication auto complete issue I had in vscode too.

**Comment by dereuromark** [comment]
I added the note about the IDE here: https://github.com/dereuromark/cakephp-ide-helper/commit/497e960efdadb296ce23629e915592bf02f8fd90

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ide-helper-extra/pull/3

**Pull request closed without merging**
