### PR TITLE
allow PHPUnit 11

### PR DESCRIPTION
**Pull request by LordSimal**
No idea what the rest of the failing tests are. You will need to fix them yourself

### CODE REVIEW

**Comment by dereuromark** [comment]
Looks like plugin loading doesnt work anymore in 5.next

**Comment by LordSimal** [comment]
Probably related to https://github.com/cakephp/cakephp/pull/17639

**Comment by dereuromark** [comment]
There is sth wrong with it

$this->loadPlugins(['Awesome', 'Controllers', 'MyNamespace/MyPlugin', 'Relations', 'Shim', 'IdeHelper']);

is there, and the test passes if I execute /Task directory alone
But running all tests makes it fail

**Comment by LordSimal** [comment]
@dereuromark see my latest commit. The problem was not cake, it was you caching the model data statically and not clearing it properly

**Comment by dereuromark** [comment]
So the tests are not quite compatible for 5.0 vs 5.1
I guess we could wait till 5.1 is released and bump the dependency

Or we find a way for it to work for both to allow also 5.0.x to work with the updated changes.

**Comment by LordSimal** [comment]
I'd just do a 2.3.0 which requires cake 5.1 and thats it.

**Comment by LordSimal** [comment]
well e.g. the BannerHelper was added in 5.1
Your tests check the generated PHPStorm Meta files for an exact match.
Do you want to write seperate tests for 5.0 and 5.1 since different Commands are present by default?

**Comment by dereuromark** [comment]
We could also skip tests for 5.0 here if needed, I would in general like to keep the version constraint open a bit longer

**Pull request merged**
