### PR TITLE
Allow element names being auto-completed.

### PR DESCRIPTION
**Pull request by dereuromark**
`$this->element('...')` calls can now autocomplete the file name of the ctp template.
must return object here, but echo should still be fine..?

can someone confirm?

### CODE REVIEW

**Comment by garas** [comment]
`'deeply/nested'` is `'deeply\nested'` on Windows

**Comment by dereuromark** [comment]
@garas , No - it should not be. This is normalized inside the framework. This is not a path separator, but an element nesting tool. It only translates into a real path at the end inside the View class.

**Comment by garas** [comment]
`echo $this->element('deeply\nested');` fails on Linux, so separator must be `/`.
I can't find no separator translation in `View`.

**Comment by dereuromark** [comment]
As documented always use /
Again: this is not a DS. It is a normal slash.

**Pull request merged**
