### PR TITLE
Model events

### PR DESCRIPTION
**Pull request by toggenation**
Hi @dereuromark,

I found that when I was trying to autocomplete the callback function definitions for the Model.*  events in a Table class that they wouldn't complete (I use VSCode).

Is this PR a correct way to get that working? Not sure if it will cause problems with PHPStorm or if it is implemented correctly.

Version: Cake 4.4.5 
PHP: 8.1.10

### CODE REVIEW

**Comment by dereuromark** [comment]
Cool
Do you have an example or Screenshot how it looks like in your IDE?

**Comment by toggenation** [comment]
> 
Hi @dereuromark 

This is a screen shot of the suggestions provided before pressing enter

2022-09-19 17_27_18-● ArticlesTable php - html  Container events_system-php (events_system-php-1)  -

This is what you see after the suggestions in inserted

2022-09-19 17_27_32-● ArticlesTable php - html  Container events_system-php (events_system-php-1)  -

**Comment by dereuromark** [comment]
Do we need them for behaviors as well?

Or other callbacks like in components or helpers etc?

**Comment by toggenation** [comment]
> Do we need them for behaviors as well?
> 
> Or in general other callbacks like in components or helpers etc?

I think the Behaviors are covered in VS Code using the bmewburn.vscode-intelephense-client extension with a premium level license by adding `@mixin`  to the annotations PHPDoc block before the class. e.g.

```
/**
 * @property ...
 * @method ... 
 *
 * @mixin \Cake\ORM\Behavior\TreeBehavior
 */
class TagsTable extends Table
{
    public function recoverTree(){
        $this->recover();
    }
    public function initialize(array $config): void
    {
           // other initialize code
           
           $this->addBehavior('Tree');
    }
   
```

The ide-helper does this nicely using `bin/cake annotate models`

2022-09-19 21_15_00-Greenshot2

Not sure about Components. I will wait till I run into problems for other situations :)

**Comment by dereuromark** [comment]
@toggenation Do you want to confirm/check https://github.com/dereuromark/cakephp-ide-helper/pull/286 ?
Those should fix the remaining callbacks as per docs.

**Pull request merged**
