### PR TITLE
Synchronize annotations order with bake for Cake 3 

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**
Synchronize annotations order with https://github.com/cakephp/bake/blob/1.x/src/View/Helper/DocBlockHelper.php

### CODE REVIEW

**Comment by dereuromark** [comment]
Is this only about order or did sth else change?

**Comment by andrii-pukhalevych** [comment]
Only order. 
I see 'Copied from Bake plugin's DocBlockHelper', now its true

**Comment by andrii-pukhalevych** [comment]
Bake's DocBlockHelper does not contain `saveMany`, so I didnt move `saveMany`

**Comment by dereuromark** [comment]
I changed the order for a reason: To resolve the current mess
It now orders as follows: creating, retrieving, patching, saving, deleting
This is the case now for both 3.x and 4.x version of the plugin.

I think you might rather want to adjust Bake here IMO
Best to do that in 4.x and then backport it later to 3.x

The missing saveMany ones could also be added where needed.
Note: 3.9 is not out yet, the bake version for 3.9 should contain those, then.

Also see
- https://github.com/cakephp/bake/issues/579
- https://github.com/cakephp/bake/issues/464

**Comment by andrii-pukhalevych** [comment]
Ок, agree, then you should close this issue.
I feel we need twig template for annotations. To allow custom order and disable some unused methods.

**Pull request closed without merging**
