### PR TITLE
fix template entity annotator

### PR DESCRIPTION
**Pull request by skie**
fix template entity annotator to support expressions like ```$this->Form->create($entity, [```

### CODE REVIEW

**Comment by dereuromark** [comment]
Shouldnt we keep the [a-z] part?

**Comment by dereuromark** [comment]
What does \W do, could we also use \b ?

**Comment by skie** [comment]
> What does \W do, could we also use \b ?
\b suppose to get next word boundary, but we just want any non word character after the word we are catching, that could be just `)` or space or comma.

**Comment by dereuromark** [comment]
Thx for helping out!

**Pull request merged**
