### PR TITLE
Allow collection typehinting in templates

### PR DESCRIPTION
**Pull request by dereuromark**
Follow bake enhancement https://github.com/cakephp/bake/pull/337

### CODE REVIEW

**Comment by dereuromark** [comment]
@ondrejmirtes
I get now fails where there have not been some before - how can we make phpstan know where to find those constants etc?
https://github.com/dereuromark/cakephp-ide-helper/blob/master/tests/bootstrap.php#L9

**Comment by dereuromark** [comment]
OK, fixed with https://github.com/dereuromark/cakephp-ide-helper/pull/22

**Comment by ondrejmirtes** [comment]
@dereuromark Yes, that is the correct fix :)

**Comment by dereuromark** [comment]
Thanks for confirming :)

**Pull request merged**
